export const useSettingsStore = defineStore('settings', {
  state: () => ({
    BASE_ERROR_MESSAGE: 'Due to the high volume of requests we were unable to retrieve your data. Please try again later. - Specific error message:',
    PUBMED_BASE: 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils',
    TOXICS_RELEASE_INVENTORY_BASE_URL: 'https://enviro.epa.gov',
    GENE_SYMBOL_BASE_URL: 'https://www.ncbi.nlm.nih.gov/gene/',
    AOPS_API: 'https://aop-dev.rtpnc.epa.gov/aopws/aop/aops',
    PUBCHEM_API_URL: 'https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data',
    GENRA_URL: 'https://ccte-genra-dev.epa.gov/genra',
    ASSAY_LIST_API: 'ccdapp2/assay-lists',
    ASSAY_LIST_DETAILS_API: 'ccdapp2/assay-list-details/search/by-endpointname',
    ASSAY_LIST_DETAILS_SINGLE_CONC_API: 'ccdapp2/assay-list-single-conc/search/by-endpointname',
    ASSAY_LIST_SEARCH_API: 'ccdapp2/assay/search/start-with/',
    ASSAY_GENE_SEARCH_API: 'ccdapp1/search/assay/contain/',
    ASSAY_ENDPOINT_DETAIL_SEARCH: 'ccdapp2/assay-endpoint-detail/search/by-endpointname',
    PUBLIC_CHEMICAL_SEARCH_API: 'chemical/search/start-with/',
    CHEMICALLIST_DETAILS_DTXSIDS: 'chemical/list/search/by-name',
    CHEMICALLIST_DETAILS: 'chemical/detail/search/by-dtxsid/?projection=chemicaldetailstandard',
    CHEMICALLISTS_ALL: 'chemical/list/?projection=chemicallistall',
    CHEMICALLIST_STARTS_WITH: 'chemical/list/chemicals/search/start-with/',
    CHEMICALLIST_CONTAIN: 'chemical/list/chemicals/search/contain/',
    CHEMICAL_SEARCH_EXACT_API: 'ccdapp1/search/chemical/equal/',
    CHEMICAL_SEARCH_EQUALS_DETAILS_API: 'ccdapp1/search/chemical/equal-with-detail/',
    CHEMICAL_SEARCH_FUZZY_API: 'ccdapp1/search/chemical/contain/',
    CHEMICAL_SEARCH_STARTS_WITH_DETAILS_API: 'ccdapp1/search/chemical/start-with-details/',
    CHEMICAL_SEARCH_CONTAIN_DETAILS_API: 'ccdapp1/search/chemical/contain-with-details/',
    CHEMICAL_SEARCH_CONTAIN_DTXSID_API: 'ccdapp1/search/chemical/contain-dtxsid/',
    HELPTEXT_API: 'ccdapp1/helptext',
  }),
  getters: {
    getSettings: state => state,
  },
});
