on: 
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - dev

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
        - name: Create Comment
          run: |
            # Using GitHub API to create a comment on the PR
            PR_NUMBER=${{ github.event.pull_request.number }}
            COMMENT="/cypress"
            GITHUB_TOKEN=${{ secrets.PR_COMMENT_TOKEN }}
            COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
            curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"
