# a workflow that runs when a user enters a pull request comment
# if the user enters "/cypress" we trigger the workflow "slash-command-cypress"
name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  slash_command_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print event 🖨️
        run: |
          echo off
          echo '${{ toJson(github.event) }}'
          echo 'PR ID: ${{ github.event.issue.number }}'
          
      - name: Find the PR branch name 
        id: pr
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")
          BRANCH_NAME=$(echo "$RESPONSE" | jq -r '.head.ref')
          echo "Branch name: $BRANCH_NAME"
          echo "::set-output name=branch_name::$BRANCH_NAME"  # Set the branch_name output

      - name: Slash Command Dispatch
        # https://github.com/peter-evans/slash-command-dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          # use personal token to be able to trigger more workflows
          token: ${{ secrets.CYPRESS_REPO_TOKEN }}
          # the personal token to post the comment emoji
          reaction-token: ${{ secrets.CYPRESS_REPO_TOKEN }}
          permission: none
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}
            ref=${{ steps.pr.outputs.branch_name  }}
          commands: |
            cypress
